DATASET:
  NAME: kinetics400
  ANNOTATION:
    TYPE: csv
    FILES:
      - 'data/kinetics/kinetics400/train.csv'
      - 'data/kinetics/kinetics400/validate.csv'
      - 'data/kinetics/kinetics400/test.csv'
OUTPUT_DIR: '/data/01/action_dataset/kinetics/videos'
NUM_WORKERS: 24
DROP_DUPLICATES: true
SHUFFLE: false
MIN_SIZE: 256
NUM_ATTEMPTS: 10
