DATASET:
  NAME: kinetics400
  ANNOTATION:
    TYPE: csv
    FILES:
      - 'data/kinetics/kinetics400/train.csv'
      - 'data/kinetics/kinetics400/validate.csv'
      - 'data/kinetics/kinetics400/test.csv'
OUTPUT_DIR: '/data/kinetics/videos'
