DATASET:
  NAME: kinetics700
  ANNOTATION:
    TYPE: csv
    FILES:
      - 'data/kinetics/kinetics700/train.csv'
      - 'data/kinetics/kinetics700/validate.csv'
      - 'data/kinetics/kinetics700/test.csv'
OUTPUT_DIR: '/data/01/action_dataset/kinetics/videos'
